{% set name = "maestral" %}
{% set version = "0.5.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 2c7d0eb44f3446228772077d0b8d12b19755054c366c203dc5c3cd32a2864d4d

build:
  number: 0
  entry_points:
    - maestral=maestral.cli:main
  noarch: "python"
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - blinker
    - click >=7.0
    - dropbox >=9.4.0
    - keyring >=19.0.0
    - keyrings.alt >=3.0.0
    - pyqt
    - pyro5
    - python >=3.6
    - requests
    - setuptools
    - u-msgpack-python
    - watchdog

test:
  imports:
    - maestral
  commands:
    - maestral --help

about:
  home: "https://github.com/SamSchott/maestral"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.txt"
  summary: "Open-source Dropbox client for macOS and Linux."
  dev_url: "https://github.com/SamSchott/maestral"

extra:
  recipe-maintainers:
    - tschoonj
