{% set name = "maestral" %}
{% set version = "0.6.1.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54a3f4f2df5e3fbd761f42f471ef44bbf9e8b40064338e793dfdeb2e8dff5525

build:
  number: 0
  entry_points:
    - maestral=maestral.cli:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - blinker
    - click >=7.0
    - dropbox >=9.4.0
    - keyring >=19.0.0
    - keyrings.alt >=3.0.0
    - pyqt
    - pyro5
    - python >=3.6
    - requests
    - setuptools
    - u-msgpack-python
    - watchdog
    - lockfile
    - bugsnag

test:
  imports:
    - maestral
  commands:
    - maestral --help

about:
  home: https://github.com/SamSchott/maestral
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Open-source Dropbox client for macOS and Linux.
  dev_url: https://github.com/SamSchott/maestral

extra:
  recipe-maintainers:
    - tschoonj
